baseURL = 'https://fieldsolutions.us/'
languageCode = 'en-us'
title = 'Field Solutions'

# Clean up the site by disabling extra pages we don't need
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]